---
- name: Successfully healed ImportantApp
  hosts: localhost
  connection: local
  tasks:
  - name: Close incident
    servicenow.itsm.incident:
      number: "{{ incident_record_number }}"
      state: resolved
      close_code: "Solved Remotely (Permanently)"
      close_notes: "Closed"
      caller: "admin"
      description: "Issue has been auto-remediated, ImportantApp is now accessible"
      short_description: "{{ ansible_date_time.iso8601_micro }}"

