---
- name: Deploy importantapp
  hosts: aws_rhel8
  become: true
  tasks:
    - name: clean slate
      ansible.builtin.command:
        cmd: "subscription-manager clean"

    - name: deploy importantapp
      ansible.builtin.include_role:
        name: "importantapp"
