---
- name: Install nginx
  ansible.builtin.dnf: 
    name: nginx
    state: present
  notify: restart nginx

- name: Create site directory
  ansible.builtin.file:
    path: /var/www/
    state: directory
    recurse: true
  notify: restart nginx
    
- name: Untar archive
  ansible.builtin.unarchive:
    src: site.tar.gz
    dest: /var/www/
  register: unarchive
    
- name: manage files in /var/www/
  ansible.builtin.command: semanage fcontext -a -t httpd_sys_content_t '/var/www/html(/.*)?'
  ignore_errors: True

- name: Apply new SELinux file context to filesystem
  ansible.builtin.command: restorecon -irv /var/www/html/
    
- name: Create site directory
  ansible.builtin.copy:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf
  notify: restart nginx
    
- name: Start nginx service
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: true
    
- name: Add http firewall rule
  ansible.posix.firewalld:
    service: http
    permanent: true
    state: enabled
  notify: reload firewall
    
- name: Refresh handlers
  meta: flush_handlers
    
- name: Wait for webapp to be available
  ansible.builtin.wait_for:
    port: 443
  delegate_to: localhost
